version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
      - auth
    networks:
      - app-network

  api:
    build: ./backend/api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/api:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/sinuzoid
    depends_on:
      - db
    networks:
      - app-network

  auth:
    build: ./backend/auth
    ports:
      - "9000:9000"
    volumes:
      - ./backend/auth:/var/www
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/sinuzoid
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/auth:/var/www
    depends_on:
      - auth
    networks:
      - app-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sinuzoid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: