version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/sinuzoid
    depends_on:
      - db
    networks:
      - backend-network

  auth:
    build: ./auth
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/sinuzoid
    depends_on:
      - db
    networks:
      - backend-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./auth:/var/www
    depends_on:
      - auth
    networks:
      - backend-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sinuzoid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  postgres_data: